/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTemplatesRouteImport } from './routes/_app.templates'
import { Route as AppRulesRouteImport } from './routes/_app.rules'
import { Route as AppMailRouteImport } from './routes/_app.mail'
import { Route as AppContactsRouteImport } from './routes/_app.contacts'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppContactsIndexRouteImport } from './routes/_app.contacts.index'
import { Route as AppSettingsSignaturesRouteImport } from './routes/_app.settings.signatures'
import { Route as AppSettingsPreferencesRouteImport } from './routes/_app.settings.preferences'
import { Route as AppSettingsMailRouteImport } from './routes/_app.settings.mail'
import { Route as AppMailSnoozedRouteImport } from './routes/_app.mail.snoozed'
import { Route as AppMailSentRouteImport } from './routes/_app.mail.sent'
import { Route as AppMailSearchRouteImport } from './routes/_app.mail.search'
import { Route as AppMailOtherRouteImport } from './routes/_app.mail.other'
import { Route as AppMailJunkRouteImport } from './routes/_app.mail.junk'
import { Route as AppMailInboxRouteImport } from './routes/_app.mail.inbox'
import { Route as AppMailFocusedRouteImport } from './routes/_app.mail.focused'
import { Route as AppMailFlaggedRouteImport } from './routes/_app.mail.flagged'
import { Route as AppMailDraftsRouteImport } from './routes/_app.mail.drafts'
import { Route as AppMailDeletedRouteImport } from './routes/_app.mail.deleted'
import { Route as AppMailArchiveRouteImport } from './routes/_app.mail.archive'
import { Route as AppContactsContactIdRouteImport } from './routes/_app.contacts.$contactId'
import { Route as AppCalendarWeekRouteImport } from './routes/_app.calendar.week'
import { Route as AppCalendarMonthRouteImport } from './routes/_app.calendar.month'
import { Route as AppCalendarDayRouteImport } from './routes/_app.calendar.day'
import { Route as AppMailFolderFolderIdRouteImport } from './routes/_app.mail.folder.$folderId'
import { Route as AppMailCategoryCategoryIdRouteImport } from './routes/_app.mail.category.$categoryId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppMailRoute = AppMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppSettingsSignaturesRoute = AppSettingsSignaturesRouteImport.update({
  id: '/settings/signatures',
  path: '/settings/signatures',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPreferencesRoute = AppSettingsPreferencesRouteImport.update({
  id: '/settings/preferences',
  path: '/settings/preferences',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsMailRoute = AppSettingsMailRouteImport.update({
  id: '/settings/mail',
  path: '/settings/mail',
  getParentRoute: () => AppRoute,
} as any)
const AppMailSnoozedRoute = AppMailSnoozedRouteImport.update({
  id: '/snoozed',
  path: '/snoozed',
  getParentRoute: () => AppMailRoute,
} as any)
const AppMailSentRoute = AppMailSentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => AppMailRoute,
} as any)
const AppMailSearchRoute = AppMailSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppMailRoute,
} as any)
const AppMailOtherRoute = AppMailOtherRouteImport.update({
  id: '/other',
  path: '/other',
  getParentRoute: () => AppMailRoute,
} as any)
const AppMailJunkRoute = AppMailJunkRouteImport.update({
  id: '/junk',
  path: '/junk',
  getParentRoute: () => AppMailRoute,
} as any)
const AppMailInboxRoute = AppMailInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppMailRoute,
} as any)
const AppMailFocusedRoute = AppMailFocusedRouteImport.update({
  id: '/focused',
  path: '/focused',
  getParentRoute: () => AppMailRoute,
} as any)
const AppMailFlaggedRoute = AppMailFlaggedRouteImport.update({
  id: '/flagged',
  path: '/flagged',
  getParentRoute: () => AppMailRoute,
} as any)
const AppMailDraftsRoute = AppMailDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => AppMailRoute,
} as any)
const AppMailDeletedRoute = AppMailDeletedRouteImport.update({
  id: '/deleted',
  path: '/deleted',
  getParentRoute: () => AppMailRoute,
} as any)
const AppMailArchiveRoute = AppMailArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AppMailRoute,
} as any)
const AppContactsContactIdRoute = AppContactsContactIdRouteImport.update({
  id: '/$contactId',
  path: '/$contactId',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppCalendarWeekRoute = AppCalendarWeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => AppCalendarRoute,
} as any)
const AppCalendarMonthRoute = AppCalendarMonthRouteImport.update({
  id: '/month',
  path: '/month',
  getParentRoute: () => AppCalendarRoute,
} as any)
const AppCalendarDayRoute = AppCalendarDayRouteImport.update({
  id: '/day',
  path: '/day',
  getParentRoute: () => AppCalendarRoute,
} as any)
const AppMailFolderFolderIdRoute = AppMailFolderFolderIdRouteImport.update({
  id: '/folder/$folderId',
  path: '/folder/$folderId',
  getParentRoute: () => AppMailRoute,
} as any)
const AppMailCategoryCategoryIdRoute =
  AppMailCategoryCategoryIdRouteImport.update({
    id: '/category/$categoryId',
    path: '/category/$categoryId',
    getParentRoute: () => AppMailRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof AppCalendarRouteWithChildren
  '/contacts': typeof AppContactsRouteWithChildren
  '/mail': typeof AppMailRouteWithChildren
  '/rules': typeof AppRulesRoute
  '/templates': typeof AppTemplatesRoute
  '/calendar/day': typeof AppCalendarDayRoute
  '/calendar/month': typeof AppCalendarMonthRoute
  '/calendar/week': typeof AppCalendarWeekRoute
  '/contacts/$contactId': typeof AppContactsContactIdRoute
  '/mail/archive': typeof AppMailArchiveRoute
  '/mail/deleted': typeof AppMailDeletedRoute
  '/mail/drafts': typeof AppMailDraftsRoute
  '/mail/flagged': typeof AppMailFlaggedRoute
  '/mail/focused': typeof AppMailFocusedRoute
  '/mail/inbox': typeof AppMailInboxRoute
  '/mail/junk': typeof AppMailJunkRoute
  '/mail/other': typeof AppMailOtherRoute
  '/mail/search': typeof AppMailSearchRoute
  '/mail/sent': typeof AppMailSentRoute
  '/mail/snoozed': typeof AppMailSnoozedRoute
  '/settings/mail': typeof AppSettingsMailRoute
  '/settings/preferences': typeof AppSettingsPreferencesRoute
  '/settings/signatures': typeof AppSettingsSignaturesRoute
  '/contacts/': typeof AppContactsIndexRoute
  '/mail/category/$categoryId': typeof AppMailCategoryCategoryIdRoute
  '/mail/folder/$folderId': typeof AppMailFolderFolderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof AppCalendarRouteWithChildren
  '/mail': typeof AppMailRouteWithChildren
  '/rules': typeof AppRulesRoute
  '/templates': typeof AppTemplatesRoute
  '/calendar/day': typeof AppCalendarDayRoute
  '/calendar/month': typeof AppCalendarMonthRoute
  '/calendar/week': typeof AppCalendarWeekRoute
  '/contacts/$contactId': typeof AppContactsContactIdRoute
  '/mail/archive': typeof AppMailArchiveRoute
  '/mail/deleted': typeof AppMailDeletedRoute
  '/mail/drafts': typeof AppMailDraftsRoute
  '/mail/flagged': typeof AppMailFlaggedRoute
  '/mail/focused': typeof AppMailFocusedRoute
  '/mail/inbox': typeof AppMailInboxRoute
  '/mail/junk': typeof AppMailJunkRoute
  '/mail/other': typeof AppMailOtherRoute
  '/mail/search': typeof AppMailSearchRoute
  '/mail/sent': typeof AppMailSentRoute
  '/mail/snoozed': typeof AppMailSnoozedRoute
  '/settings/mail': typeof AppSettingsMailRoute
  '/settings/preferences': typeof AppSettingsPreferencesRoute
  '/settings/signatures': typeof AppSettingsSignaturesRoute
  '/contacts': typeof AppContactsIndexRoute
  '/mail/category/$categoryId': typeof AppMailCategoryCategoryIdRoute
  '/mail/folder/$folderId': typeof AppMailFolderFolderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/calendar': typeof AppCalendarRouteWithChildren
  '/_app/contacts': typeof AppContactsRouteWithChildren
  '/_app/mail': typeof AppMailRouteWithChildren
  '/_app/rules': typeof AppRulesRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/calendar/day': typeof AppCalendarDayRoute
  '/_app/calendar/month': typeof AppCalendarMonthRoute
  '/_app/calendar/week': typeof AppCalendarWeekRoute
  '/_app/contacts/$contactId': typeof AppContactsContactIdRoute
  '/_app/mail/archive': typeof AppMailArchiveRoute
  '/_app/mail/deleted': typeof AppMailDeletedRoute
  '/_app/mail/drafts': typeof AppMailDraftsRoute
  '/_app/mail/flagged': typeof AppMailFlaggedRoute
  '/_app/mail/focused': typeof AppMailFocusedRoute
  '/_app/mail/inbox': typeof AppMailInboxRoute
  '/_app/mail/junk': typeof AppMailJunkRoute
  '/_app/mail/other': typeof AppMailOtherRoute
  '/_app/mail/search': typeof AppMailSearchRoute
  '/_app/mail/sent': typeof AppMailSentRoute
  '/_app/mail/snoozed': typeof AppMailSnoozedRoute
  '/_app/settings/mail': typeof AppSettingsMailRoute
  '/_app/settings/preferences': typeof AppSettingsPreferencesRoute
  '/_app/settings/signatures': typeof AppSettingsSignaturesRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
  '/_app/mail/category/$categoryId': typeof AppMailCategoryCategoryIdRoute
  '/_app/mail/folder/$folderId': typeof AppMailFolderFolderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/contacts'
    | '/mail'
    | '/rules'
    | '/templates'
    | '/calendar/day'
    | '/calendar/month'
    | '/calendar/week'
    | '/contacts/$contactId'
    | '/mail/archive'
    | '/mail/deleted'
    | '/mail/drafts'
    | '/mail/flagged'
    | '/mail/focused'
    | '/mail/inbox'
    | '/mail/junk'
    | '/mail/other'
    | '/mail/search'
    | '/mail/sent'
    | '/mail/snoozed'
    | '/settings/mail'
    | '/settings/preferences'
    | '/settings/signatures'
    | '/contacts/'
    | '/mail/category/$categoryId'
    | '/mail/folder/$folderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/mail'
    | '/rules'
    | '/templates'
    | '/calendar/day'
    | '/calendar/month'
    | '/calendar/week'
    | '/contacts/$contactId'
    | '/mail/archive'
    | '/mail/deleted'
    | '/mail/drafts'
    | '/mail/flagged'
    | '/mail/focused'
    | '/mail/inbox'
    | '/mail/junk'
    | '/mail/other'
    | '/mail/search'
    | '/mail/sent'
    | '/mail/snoozed'
    | '/settings/mail'
    | '/settings/preferences'
    | '/settings/signatures'
    | '/contacts'
    | '/mail/category/$categoryId'
    | '/mail/folder/$folderId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/calendar'
    | '/_app/contacts'
    | '/_app/mail'
    | '/_app/rules'
    | '/_app/templates'
    | '/_app/calendar/day'
    | '/_app/calendar/month'
    | '/_app/calendar/week'
    | '/_app/contacts/$contactId'
    | '/_app/mail/archive'
    | '/_app/mail/deleted'
    | '/_app/mail/drafts'
    | '/_app/mail/flagged'
    | '/_app/mail/focused'
    | '/_app/mail/inbox'
    | '/_app/mail/junk'
    | '/_app/mail/other'
    | '/_app/mail/search'
    | '/_app/mail/sent'
    | '/_app/mail/snoozed'
    | '/_app/settings/mail'
    | '/_app/settings/preferences'
    | '/_app/settings/signatures'
    | '/_app/contacts/'
    | '/_app/mail/category/$categoryId'
    | '/_app/mail/folder/$folderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rules': {
      id: '/_app/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mail': {
      id: '/_app/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof AppMailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/settings/signatures': {
      id: '/_app/settings/signatures'
      path: '/settings/signatures'
      fullPath: '/settings/signatures'
      preLoaderRoute: typeof AppSettingsSignaturesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/preferences': {
      id: '/_app/settings/preferences'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof AppSettingsPreferencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/mail': {
      id: '/_app/settings/mail'
      path: '/settings/mail'
      fullPath: '/settings/mail'
      preLoaderRoute: typeof AppSettingsMailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mail/snoozed': {
      id: '/_app/mail/snoozed'
      path: '/snoozed'
      fullPath: '/mail/snoozed'
      preLoaderRoute: typeof AppMailSnoozedRouteImport
      parentRoute: typeof AppMailRoute
    }
    '/_app/mail/sent': {
      id: '/_app/mail/sent'
      path: '/sent'
      fullPath: '/mail/sent'
      preLoaderRoute: typeof AppMailSentRouteImport
      parentRoute: typeof AppMailRoute
    }
    '/_app/mail/search': {
      id: '/_app/mail/search'
      path: '/search'
      fullPath: '/mail/search'
      preLoaderRoute: typeof AppMailSearchRouteImport
      parentRoute: typeof AppMailRoute
    }
    '/_app/mail/other': {
      id: '/_app/mail/other'
      path: '/other'
      fullPath: '/mail/other'
      preLoaderRoute: typeof AppMailOtherRouteImport
      parentRoute: typeof AppMailRoute
    }
    '/_app/mail/junk': {
      id: '/_app/mail/junk'
      path: '/junk'
      fullPath: '/mail/junk'
      preLoaderRoute: typeof AppMailJunkRouteImport
      parentRoute: typeof AppMailRoute
    }
    '/_app/mail/inbox': {
      id: '/_app/mail/inbox'
      path: '/inbox'
      fullPath: '/mail/inbox'
      preLoaderRoute: typeof AppMailInboxRouteImport
      parentRoute: typeof AppMailRoute
    }
    '/_app/mail/focused': {
      id: '/_app/mail/focused'
      path: '/focused'
      fullPath: '/mail/focused'
      preLoaderRoute: typeof AppMailFocusedRouteImport
      parentRoute: typeof AppMailRoute
    }
    '/_app/mail/flagged': {
      id: '/_app/mail/flagged'
      path: '/flagged'
      fullPath: '/mail/flagged'
      preLoaderRoute: typeof AppMailFlaggedRouteImport
      parentRoute: typeof AppMailRoute
    }
    '/_app/mail/drafts': {
      id: '/_app/mail/drafts'
      path: '/drafts'
      fullPath: '/mail/drafts'
      preLoaderRoute: typeof AppMailDraftsRouteImport
      parentRoute: typeof AppMailRoute
    }
    '/_app/mail/deleted': {
      id: '/_app/mail/deleted'
      path: '/deleted'
      fullPath: '/mail/deleted'
      preLoaderRoute: typeof AppMailDeletedRouteImport
      parentRoute: typeof AppMailRoute
    }
    '/_app/mail/archive': {
      id: '/_app/mail/archive'
      path: '/archive'
      fullPath: '/mail/archive'
      preLoaderRoute: typeof AppMailArchiveRouteImport
      parentRoute: typeof AppMailRoute
    }
    '/_app/contacts/$contactId': {
      id: '/_app/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof AppContactsContactIdRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/calendar/week': {
      id: '/_app/calendar/week'
      path: '/week'
      fullPath: '/calendar/week'
      preLoaderRoute: typeof AppCalendarWeekRouteImport
      parentRoute: typeof AppCalendarRoute
    }
    '/_app/calendar/month': {
      id: '/_app/calendar/month'
      path: '/month'
      fullPath: '/calendar/month'
      preLoaderRoute: typeof AppCalendarMonthRouteImport
      parentRoute: typeof AppCalendarRoute
    }
    '/_app/calendar/day': {
      id: '/_app/calendar/day'
      path: '/day'
      fullPath: '/calendar/day'
      preLoaderRoute: typeof AppCalendarDayRouteImport
      parentRoute: typeof AppCalendarRoute
    }
    '/_app/mail/folder/$folderId': {
      id: '/_app/mail/folder/$folderId'
      path: '/folder/$folderId'
      fullPath: '/mail/folder/$folderId'
      preLoaderRoute: typeof AppMailFolderFolderIdRouteImport
      parentRoute: typeof AppMailRoute
    }
    '/_app/mail/category/$categoryId': {
      id: '/_app/mail/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/mail/category/$categoryId'
      preLoaderRoute: typeof AppMailCategoryCategoryIdRouteImport
      parentRoute: typeof AppMailRoute
    }
  }
}

interface AppCalendarRouteChildren {
  AppCalendarDayRoute: typeof AppCalendarDayRoute
  AppCalendarMonthRoute: typeof AppCalendarMonthRoute
  AppCalendarWeekRoute: typeof AppCalendarWeekRoute
}

const AppCalendarRouteChildren: AppCalendarRouteChildren = {
  AppCalendarDayRoute: AppCalendarDayRoute,
  AppCalendarMonthRoute: AppCalendarMonthRoute,
  AppCalendarWeekRoute: AppCalendarWeekRoute,
}

const AppCalendarRouteWithChildren = AppCalendarRoute._addFileChildren(
  AppCalendarRouteChildren,
)

interface AppContactsRouteChildren {
  AppContactsContactIdRoute: typeof AppContactsContactIdRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
}

const AppContactsRouteChildren: AppContactsRouteChildren = {
  AppContactsContactIdRoute: AppContactsContactIdRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
}

const AppContactsRouteWithChildren = AppContactsRoute._addFileChildren(
  AppContactsRouteChildren,
)

interface AppMailRouteChildren {
  AppMailArchiveRoute: typeof AppMailArchiveRoute
  AppMailDeletedRoute: typeof AppMailDeletedRoute
  AppMailDraftsRoute: typeof AppMailDraftsRoute
  AppMailFlaggedRoute: typeof AppMailFlaggedRoute
  AppMailFocusedRoute: typeof AppMailFocusedRoute
  AppMailInboxRoute: typeof AppMailInboxRoute
  AppMailJunkRoute: typeof AppMailJunkRoute
  AppMailOtherRoute: typeof AppMailOtherRoute
  AppMailSearchRoute: typeof AppMailSearchRoute
  AppMailSentRoute: typeof AppMailSentRoute
  AppMailSnoozedRoute: typeof AppMailSnoozedRoute
  AppMailCategoryCategoryIdRoute: typeof AppMailCategoryCategoryIdRoute
  AppMailFolderFolderIdRoute: typeof AppMailFolderFolderIdRoute
}

const AppMailRouteChildren: AppMailRouteChildren = {
  AppMailArchiveRoute: AppMailArchiveRoute,
  AppMailDeletedRoute: AppMailDeletedRoute,
  AppMailDraftsRoute: AppMailDraftsRoute,
  AppMailFlaggedRoute: AppMailFlaggedRoute,
  AppMailFocusedRoute: AppMailFocusedRoute,
  AppMailInboxRoute: AppMailInboxRoute,
  AppMailJunkRoute: AppMailJunkRoute,
  AppMailOtherRoute: AppMailOtherRoute,
  AppMailSearchRoute: AppMailSearchRoute,
  AppMailSentRoute: AppMailSentRoute,
  AppMailSnoozedRoute: AppMailSnoozedRoute,
  AppMailCategoryCategoryIdRoute: AppMailCategoryCategoryIdRoute,
  AppMailFolderFolderIdRoute: AppMailFolderFolderIdRoute,
}

const AppMailRouteWithChildren =
  AppMailRoute._addFileChildren(AppMailRouteChildren)

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRouteWithChildren
  AppContactsRoute: typeof AppContactsRouteWithChildren
  AppMailRoute: typeof AppMailRouteWithChildren
  AppRulesRoute: typeof AppRulesRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppSettingsMailRoute: typeof AppSettingsMailRoute
  AppSettingsPreferencesRoute: typeof AppSettingsPreferencesRoute
  AppSettingsSignaturesRoute: typeof AppSettingsSignaturesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRouteWithChildren,
  AppContactsRoute: AppContactsRouteWithChildren,
  AppMailRoute: AppMailRouteWithChildren,
  AppRulesRoute: AppRulesRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppSettingsMailRoute: AppSettingsMailRoute,
  AppSettingsPreferencesRoute: AppSettingsPreferencesRoute,
  AppSettingsSignaturesRoute: AppSettingsSignaturesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
